backports: import optee-os & optee-client v4.9.0 from meta-arm
Remove the old recipes imported in this layer's commit [1] as well as the old
PTX patchstack from commit [2] and the follow-up backports from [3] by reverting
all and resolving the resulting conflicts

  $ git revert -n 3a111bcedb6f 121b28362327 15f82ec09ba8
  $ git add recipes-security/optee/optee-client_%.bbappend \
            recipes-security/optee/optee-os_%.bbappend

import the recipe from commit [4] on the wrynose branch of meta-arm

  $ ORIGIN=meta-arm/recipes-security
  $ DESTINATION=backports-meta-arm-wrynose/recipes-security
  $ SELECTION="optee/optee-os_4.9.0.bb optee/optee.inc optee/optee-os.inc \
               optee/optee-os-ts.inc optee/optee-os_%.bbappend \
	       trusted-services/ts-uuid.inc \
               optee/optee-client_4.9.0.bb optee/optee-client.inc \
               optee/optee-client"
  $ mkdir -p ${DESTINATION}
  $ git -C <PATH_TO_meta-arm> archive caa36c53f796:${ORIGIN} ${SELECTION} | \
    tar -x -C ${DESTINATION}
  $ find ${DESTINATION} -type f | \
    xargs -d "\n" sed -i "s,require recipes-security,require ${DESTINATION},g"

partially revert meta-arm commit [5] to fix the source location S that is
necessary from walnascar onwards but which breaks things in scarthgap, add

  OPTEE_SRC_URI_BRANCH_OR_TAG = "branch=master"

to not run into

  ERROR: ExpansionError during parsing <PATH_TO_BSP>/YOCTO.BSP-Skov-DOL-scarthgap/poky/../meta-skov-cpu-bsp/backports-meta-arm-wrynose/recipes-security/optee/optee-os_4.9.0.bb
  bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: Conflicting revisions (c2b0684fcd89929976a8726e6e3af922b48dd2c7 from SRCREV and 4.9.0 from the url) found, please specify one valid value

and without a customized patchstack that allows for that switch back from
"imx-mx8mp" to the less generic

  OPTEEMACHINE:imx8s-cpu = "imx-mx8mpevk"

to avoid breaking the build with

  core/arch/arm/plat-imx/conf.mk:288: *** Unsupported PLATFORM_FLAVOR "mx8mp".  Stop.

[1] 15f82ec09ba8 ("backports: import optee-os & optee-client v4.60 from meta-arm")
[2] 121b28362327 ("optee-os: update to v4.6/customers/skov/imx6/20250820-1 (4.6.0 -> 4.6.0)")
[3] 3a111bcedb6f ("backports: optee-os: backport commits")
[4] caa36c53f796 ("ci: enable testimage coverage for Corstone-1000 A320 FVP")
[5] eea748608c82 ("arm: WORKDIR fixes")