backports: import optee-test & optee-os-tadevkit v4.9.0 from meta-arm
Remove the old recipes imported in this layer's commit [1] by reverting it and
resolving the resulting conflicts as well as restore still required files that
have been removed by the revert

  $ git revert -n 9bd3dc34cf2d
  $ git restore --staged --worktree --source=HEAD^ \
        recipes-security/optee/optee-test_%.bbappend \
        recipes-security/optee/optee-os-tadevkit_%.bbappend \
        recipes-security/optee/optee-os-tadevkit

import meta-arm's recipes from commit [2]

  $ ORIGIN=meta-arm/recipes-security/optee
  $ DESTINATION=backports-meta-arm-wrynose/recipes-security/optee
  $ SELECTION="optee-test_4.9.0.bb optee-test.inc optee-test \
               optee-os-tadevkit_4.9.0.bb"
  $ mkdir -p ${DESTINATION}
  $ git -C <PATH_TO_meta-arm> archive caa36c53f796:${ORIGIN} ${SELECTION} | \
    tar -x -C ${DESTINATION}
  $ find ${DESTINATION} -type f | \
    xargs -d "\n" sed -i "s,require recipes-security/optee,require ${DESTINATION},g"

and add

  OPTEE_SRC_URI_BRANCH_OR_TAG = "branch=master"

to optee-test_%.bbappend to not run into

  ERROR: ExpansionError during parsing <PATH_TO_BSP>/YOCTO.BSP-Skov-DOL-scarthgap/poky/../meta-skov-cpu-bsp/backports-meta-arm-wrynose/recipes-security/optee/optee-test_4.9.0.bb
  bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: Conflicting revisions (b27648ea8472cceceb8dda368a965c709066f7aa from SRCREV and 4.9.0 from the url) found, please specify one valid value

[1] 9bd3dc34cf2d ("backports: import optee-test & optee-os-tadevkit v4.6.0 from meta-arm")
[2] caa36c53f796 ("ci: enable testimage coverage for Corstone-1000 A320 FVP")
[3] eea748608c82 ("arm: WORKDIR fixes")